### ISSUE TITLE
How to implement a sticky service?

### ISSUE THREAD

**Issue by kkar** [quilkin/LocationService#2]
Is there a way for LocationService code to be running even if the app is closed via the phone's running apps screen? Thank you.

**Comment by quilkin** [comment]
I've had to move everything to a [new folder](https://github.com/quilkin/WhereIAm) . The background code continues to run if the app is closed, and starts to run automatically after reboot.

**Comment by kkar** [comment]
Thank you so much for this! I am asking because i noticed that if i close the app and re-open it, the "start service" button is enabled and the "stop" button is disabled. Is there a chance that i was looking to an older version of this? AWESOME WORK btw!!! Thanks again for this!

**Comment by quilkin** [comment]
I haven't got the button disables working correctly, because I haven't yet found out a way for the app to find out if the service is already running! I need to add that to the 'ToDo' list.

**Comment by kkar** [comment]
Thanks! Closing the issue! :)
